<% def env(a, b); e = ENV["obtvse_#{a}"]; e ? e : b; end %>

name:    <%= env :name,    'Dan Vera' %>
twitter: <%= env :twitter, 'drkyro' %>
github:  <%= env :github,  'drkyro'  %>
email:   <%= env :email,   'dan@yovu.co'  %>
about:   <%= env :about,   'Software Engineer, Blogger, Businessmen, Gamer and Anime Lover.' %>

# Google Analytics
ga_id:   <%= env :ga,      ''  %>
